### ISSUE TITLE
how to play ai?

### ISSUE THREAD

**Issue by cloudjanak** [mrshanahan/scrabble#1]
is it possiable like below in web-site 
pass the current board and it will return all playable words with starting position and direction.

http://www.lexicalwordfinder.com/?game=Words_With_Friends&layout=1&tiles=gtsfsdf&board=----------------------------------------------------------------------------------------------------------------hello------------------------------------------------------------------------------------------------------------&lexicon=wwf

**Comment by mrshanahan** [comment]
Hey Janak,

This was an old school project, and unfortunately I abandoned it before
getting around to making an AI, so it doesn't have much functionality. Good
luck though!
- Matt

**Comment by cloudjanak** [comment]
can you suggest me how i can make an ai player for this where we can pass current board position and rack tiles and it will return all playable words on board with start position and direction

**Comment by mrshanahan** [comment]
Hey Janak,

Sure! (Also, sorry ahead of time for the lag in responses; either you work
very late or we're in different time zones.) One computationally exhaustive
way to do it (and I believe the way I was thinking about implementing the
AI at the time) is to get the set of all spaces for words on the board,
match these with a pre-defined dictionary, then calculate the highest score
from among those options. For example, if you had a five-by-five board with
the word "TAG" down the middle:

---
- \- T - -
- \- A - -
- \- G - -
  - - - - -

Then you would have the vectors "-TAG-", "--T--", "--A--", "--G--", and
then all of their subcomponents (e.g. "TAG-", "-TAG", "-T--", "T--", etc.).
You could use a regex to filter a predefined dictionary with words that
match those vectors, filter again based on the words in your rack (or vice
versa), and then rate them by score. This is ignoring double/triple
word/letter score tiles, but those can be easily added on top of that. Of
course this only looks for the current best move, so you could also make a
less intensive scoring mechanism that can then look ahead and predict which
series of future moves would be best, but that's probably not as necessary
in Scrabble as it is in e.g. chess.

Hope that was somewhat helpful!
- Matt
